name: 'Release Builds'

on:
  push:
    tags:
      - 'v*'

jobs:

  release:
    name: 'Create Release from Tag'
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

  build:
    name: 'Build & Upload ${{ matrix.OSes }} Release'
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        OSes: ['windows', 'darwin', 'linux']

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Golang Environment'
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'

      - name: 'Build ${{ matrix.OSes }} binary'
        run: |
          GOOS=${{ matrix.OSes }} \
          go build -o mrglass_${{ matrix.OSes }}

      - name: 'Upload Release Assets'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./mrglass_${{ matrix.OSes }}
          asset_name: mrglass_${{ matrix.OSes }}
          asset_content_type: application/octet-stream

